server:
  port: 8083

spring:
  application:
    name: cities-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3306/cities_service?serverTimezone=UTC
      username: root
      password:
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect





