server:
  port: 8082

spring:
  application:
    name: hotels-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3306/hotels_service?serverTimezone=UTC
      username: root
      password: 
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect




